exo <- read.csv("exo.csv")
str(exo)
library(caTools)
set.seed(3000)
spl = sample.split(exo$Habitable, SplitRatio = 0.7)
Train = subset(exo, spl == TRUE)
Test = subset(exo, spl == FALSE)
library("rpart")
library(rpart.plot)
ExoTree = rpart(Habitable ~ . , data = Train, method="class", minbucket=25)
prp(ExoTree)
PredictCART = predict(ExoTree, newdata = Test, type = "class")
table(Test$Habitable, PredictCART)
